import { FastifyInstance } from 'fastify';
import { ZodTypeProvider } from 'fastify-type-provider-zod';
import { z } from 'zod';
import { requireRole } from '../../plugins/auth.js';
import { ingestBiomarker, searchBiomarkersBySimilarity } from './service.js';

const BiomarkerFeatureSchema = z.object({
  gender: z.string().optional(),
  age_estimate: z.number().optional(),
  features: z.array(z.string()).optional()
});

const BiomarkerPayloadSchema = z.object({
  subjectId: z.string().min(3),
  embedding: z.array(z.number()),
  confidence: z.number().min(0).max(1),
  phenotypicMetadata: BiomarkerFeatureSchema.optional(),
  featureTags: z.array(z.string()).optional(),
  lastSeenLocationId: z.string().optional()
});

export async function biomarkerRoutes(app: FastifyInstance) {
  const server = app.withTypeProvider<ZodTypeProvider>();

  // Ingest a new Biomarker / Facial embedding
  server.post(
    '/',
    {
      schema: {
        tags: ['Biogenetic Analytics'],
        summary: 'Ingest Facial/Biometric Vector',
        description: 'Receives and stores a high-dimensional vector for a subject generated by the visual AI arrays.',
        body: BiomarkerPayloadSchema,
        response: {
          201: z.object({ id: z.string().uuid(), message: z.string() })
        }
      },
      preHandler: [(server as any).authenticate, requireRole(['operator', 'auditor'] as any)]
    },
    async (request, reply) => {
      const tenantId = request.tenantId;
      const data = request.body as z.infer<typeof BiomarkerPayloadSchema>;

      const inserted = await ingestBiomarker({
        tenantId,
        subjectId: data.subjectId,
        embedding: data.embedding,
        confidence: data.confidence,
        phenotypicMetadata: data.phenotypicMetadata,
        featureTags: data.featureTags,
        lastSeenLocationId: data.lastSeenLocationId,
      });

      return reply.code(201).send({
        id: inserted.id,
        message: 'Biomarker neural signature successfully ingested'
      });
    }
  );

  // Search Biomarkers by Similarity Match (Simulated Euclidean Distance in SQL for array,
  // Note: in production with pgvector, we use <-> operator directly)
  server.post(
    '/search',
    {
      schema: {
        tags: ['Biogenetic Analytics'],
        summary: 'Deep Neural Similarity Search',
        description: 'Compares a target facial embedding against the entire database using distance vectors.',
        body: z.object({ targetEmbedding: z.array(z.number()) }),
        response: {
          200: z.array(z.object({
            subjectId: z.string(),
            matchPercentage: z.number(),
            features: z.array(z.string()),
            lastSeenLocationId: z.string().nullable(),
            lastSeenAt: z.string()
          }))
        }
      },
      preHandler: [(server as any).authenticate, requireRole(['operator', 'auditor'] as any)]
    },
    async (request) => {
      const tenantId = request.tenantId;
      const { targetEmbedding } = request.body as { targetEmbedding: number[] };

      return searchBiomarkersBySimilarity(tenantId, targetEmbedding);
    }
  );
};
