module.exports = {
  apps: [
    {
      name: 'backend-api',
      script: 'apps/backend-api/dist/index.js',
      cwd: '/opt/aion/app/backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
      },
      max_memory_restart: '1G',
      restart_delay: 3000,
      max_restarts: 10,
      log_file: '/opt/aion/logs/backend-api.log',
      error_file: '/opt/aion/logs/backend-api-error.log',
      out_file: '/opt/aion/logs/backend-api-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'edge-gateway',
      script: 'apps/edge-gateway/dist/index.js',
      cwd: '/opt/aion/app/backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3100,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
        GATEWAY_ID: 'gw-prod-01',
        BACKEND_API_URL: 'http://127.0.0.1:3000',
        MEDIAMTX_API_URL: 'http://127.0.0.1:9997',
        MEDIAMTX_RTSP_PORT: 8554,
        DEVICE_CONNECT_TIMEOUT_MS: 10000,
        DEVICE_PING_INTERVAL_MS: 60000,
        DEVICE_RECONNECT_MAX_ATTEMPTS: 10,
        CACHE_MAX_ENTRIES: 2000,
        CACHE_TTL_MS: 600000,
        HEARTBEAT_INTERVAL_MS: 60000,
      },
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 10,
      log_file: '/opt/aion/logs/edge-gateway.log',
      error_file: '/opt/aion/logs/edge-gateway-error.log',
      out_file: '/opt/aion/logs/edge-gateway-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
