module.exports = {
  apps: [
    {
      name: 'backend-api',
      script: 'apps/backend-api/dist/index.js',
      cwd: '/opt/aion/app/backend',
      instances: 1,
      exec_mode: 'fork', // fork mode required — WebSocket connections are stateful
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
      },
      node_args: '--max-old-space-size=768',
      max_memory_restart: '900M',
      kill_timeout: 5000,
      listen_timeout: 10000,
      restart_delay: 3000,
      max_restarts: 10,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      log_file: '/opt/aion/logs/backend-api.log',
      error_file: '/opt/aion/logs/backend-api-error.log',
      out_file: '/opt/aion/logs/backend-api-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'edge-gateway',
      script: 'apps/edge-gateway/dist/index.js',
      cwd: '/opt/aion/app/backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3100,
        HOST: '0.0.0.0',
        LOG_LEVEL: 'info',
        GATEWAY_ID: 'gw-prod-01',
        BACKEND_API_URL: 'http://127.0.0.1:3000',
        MEDIAMTX_API_URL: 'http://127.0.0.1:9997',
        MEDIAMTX_RTSP_PORT: 8554,
        DEVICE_CONNECT_TIMEOUT_MS: 10000,
        DEVICE_PING_INTERVAL_MS: 60000,
        DEVICE_RECONNECT_MAX_ATTEMPTS: 10,
        CACHE_MAX_ENTRIES: 2000,
        CACHE_TTL_MS: 600000,
        HEARTBEAT_INTERVAL_MS: 60000,
      },
      node_args: '--max-old-space-size=384',
      max_memory_restart: '450M',
      kill_timeout: 5000,
      listen_timeout: 10000,
      restart_delay: 3000,
      max_restarts: 10,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      log_file: '/opt/aion/logs/edge-gateway.log',
      error_file: '/opt/aion/logs/edge-gateway-error.log',
      out_file: '/opt/aion/logs/edge-gateway-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'dahua-monitor',
      script: 'apps/backend-api/dist/workers/dahua-stream-monitor.js',
      cwd: '/opt/aion/app/backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        GO2RTC_URL: 'http://localhost:1984',
      },
      node_args: '--max-old-space-size=256',
      max_memory_restart: '300M',
      kill_timeout: 3000,
      restart_delay: 5000,
      max_restarts: 10,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      log_file: '/opt/aion/logs/dahua-monitor.log',
      error_file: '/opt/aion/logs/dahua-monitor-error.log',
      out_file: '/opt/aion/logs/dahua-monitor-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    // ─────────────────────────────────────────────────────
    //  Vision Hub v1.2.0
    // ─────────────────────────────────────────────────────
    {
      name: 'aion-vh-orchestrator',
      script: '/opt/aion/vision-hub/orchestrator/main.js',
      cwd: '/opt/aion/vision-hub/orchestrator',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        TZ: 'America/Bogota',
        LOG_LEVEL: 'info',
        VH_HTTP_PORT: '9580',
      },
      env_file: '/etc/aion/vision-hub.env',
      max_memory_restart: '800M',
      kill_timeout: 10000,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      out_file: '/var/log/aion/orchestrator.out.log',
      error_file: '/var/log/aion/orchestrator.err.log',
    },
    {
      name: 'aion-vh-bridge',
      script: '/opt/aion/vision-hub/bridge/main.js',
      cwd: '/opt/aion/vision-hub/bridge',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: '9560',
        GO2RTC_URL: 'http://127.0.0.1:1984',
        OWL_URL: 'http://127.0.0.1:9540',
      },
      max_memory_restart: '300M',
      autorestart: true,
      out_file: '/var/log/aion/bridge.out.log',
      error_file: '/var/log/aion/bridge.err.log',
    },
  ],
};
