-- ═══════════════════════════════════════════════════════════
-- AION — Multi-tenant Seed Data
-- Tenant: a0000000-0000-0000-0000-000000000001
-- Auto-generated from 04_seed_vehicles_access.sql
-- ═══════════════════════════════════════════════════════════


-- ── Vehicles Batch 3 (300 plates) ──────────────────
INSERT INTO public.vehicles (tenant_id, site_id, plate, vehicle_type)
SELECT
  'a0000000-0000-0000-0000-000000000001',
  s.id,
  t.plate,
  t.vtype
FROM (VALUES
  ('TORRE LUCIA', 'RGS601', 'car'),
  ('TORRE LUCIA', 'MNS-958', 'car'),
  ('TORRE LUCIA', 'EMP-515', 'car'),
  ('TORRE LUCIA', 'GMV-855', 'car'),
  ('TORRE LUCIA', 'RHS-076', 'car'),
  ('TORRE LUCIA', 'KZQ-815', 'car'),
  ('TORRE LUCIA', 'JBN826', 'car'),
  ('TORRE LUCIA', 'WHX74E', 'car'),
  ('TORRE LUCIA', 'SRS74E', 'car'),
  ('TORRE LUCIA', 'XNT06H', 'car'),
  ('TORRE LUCIA', 'HVO403', 'car'),
  ('TORRE LUCIA', 'RJJ81G', 'car'),
  ('TORRE LUCIA', 'CRK416', 'car'),
  ('TORRE LUCIA', 'NMX-68G', 'car'),
  ('TORRE LUCIA', 'GEW-360', 'car'),
  ('TORRE LUCIA', 'NAG335', 'car'),
  ('TORRE LUCIA', 'LOS61G', 'car'),
  ('TORRE LUCIA', 'KHB-942', 'car'),
  ('TORRE LUCIA', 'DEV-468', 'car'),
  ('TORRE LUCIA', 'KMS887', 'car'),
  ('TORRE LUCIA', 'NNC-814', 'car'),
  ('SAN NICOLAS', 'IPT242', 'car'),
  ('SAN NICOLAS', 'QKR-228', 'car'),
  ('SAN NICOLAS', 'NWL066', 'car'),
  ('SAN NICOLAS', 'HKR-360', 'car'),
  ('SAN NICOLAS', 'GRN231', 'car'),
  ('SAN NICOLAS', 'MTX152', 'car'),
  ('SAN NICOLAS', 'VJF03D', 'car'),
  ('SAN NICOLAS', 'HYV717', 'car'),
  ('SAN NICOLAS', 'DLY139', 'car'),
  ('SAN NICOLAS', 'FIT356', 'car'),
  ('SAN NICOLAS', 'LLV190', 'car'),
  ('SAN NICOLAS', 'IEX-751', 'car'),
  ('SAN NICOLAS', 'KTT293', 'car'),
  ('SAN NICOLAS', 'NGS072', 'car'),
  ('SAN NICOLAS', 'FSZ-40F', 'car'),
  ('SAN NICOLAS', 'LRO-405', 'car'),
  ('SAN NICOLAS', 'HL-196', 'car'),
  ('SAN NICOLAS', 'FIT257', 'car'),
  ('SAN NICOLAS', 'HYU922', 'car'),
  ('SAN NICOLAS', 'JYR023', 'car'),
  ('SAN NICOLAS', 'IHU547', 'car'),
  ('SAN NICOLAS', 'KTT078', 'car'),
  ('SAN NICOLAS', 'CDK748', 'car'),
  ('SAN NICOLAS', 'EOK748', 'car'),
  ('SAN NICOLAS', 'FJR901', 'car'),
  ('SAN NICOLAS', 'UCL589', 'car'),
  ('ALBORADA', 'DFU257', 'car'),
  ('ALBORADA', 'CUN229', 'car'),
  ('ALBORADA', 'KRW362', 'car'),
  ('ALBORADA', 'BXT972', 'car'),
  ('ALBORADA', 'INF114', 'car'),
  ('ALBORADA', 'BJV825', 'car'),
  ('ALBORADA', 'EIM085', 'car'),
  ('ALBORADA', 'DEU548', 'car'),
  ('ALBORADA', 'HUH32F', 'car'),
  ('ALBORADA', 'WWB71F', 'car'),
  ('ALBORADA', 'ITN50E', 'car'),
  ('ALBORADA', 'AIG25H', 'car'),
  ('ALBORADA', 'JHT862', 'car'),
  ('ALBORADA', 'GHX036', 'car'),
  ('ALBORADA', 'KHQ693', 'car'),
  ('ALBORADA', 'JYV079', 'car'),
  ('ALBORADA', 'NPU732', 'car'),
  ('ALBORADA', 'SNQ705', 'car'),
  ('ALBORADA', 'MIX528', 'car'),
  ('ALBORADA', 'MIX523', 'car'),
  ('ALBORADA', 'NPP050', 'car'),
  ('ALBORADA', 'DFT573', 'car'),
  ('ALBORADA', 'CJY86H', 'car'),
  ('ALBORADA', 'FYZ902', 'car'),
  ('ALBORADA', 'ERM78F', 'car'),
  ('ALBORADA', 'SSJ60E', 'car'),
  ('ALBORADA', 'TRY37G', 'car'),
  ('ALBORADA', 'XSL77G', 'car'),
  ('ALBORADA', 'LLW724', 'car'),
  ('ALBORADA', 'MNX346', 'car'),
  ('ALBORADA', 'LAN432', 'car'),
  ('ALBORADA', 'HCC146', 'car'),
  ('ALBORADA', 'UZO79F', 'car'),
  ('ALBORADA', 'JOO44H', 'car'),
  ('ALBORADA', 'LQJ34G', 'car'),
  ('ALBORADA', 'KWO523', 'car'),
  ('ALBORADA', 'KWO085', 'car'),
  ('ALBORADA', 'PEJ054', 'car'),
  ('ALBORADA', 'PMQ206', 'car'),
  ('ALBORADA', 'GZN30F', 'car'),
  ('ALBORADA', 'DMK314', 'car'),
  ('ALBORADA', 'EKO366', 'car'),
  ('ALBORADA', 'INO276', 'car'),
  ('ALBORADA', 'GWW627', 'car'),
  ('ALBORADA', 'JLH36H', 'car'),
  ('ALBORADA', 'YPU05F', 'car'),
  ('ALBORADA', 'LPT238', 'car'),
  ('ALBORADA', 'MTX676', 'car'),
  ('ALBORADA', 'HZN72H', 'car'),
  ('ALBORADA', 'ZAA64F', 'car'),
  ('ALBORADA', 'XYQ15F', 'car'),
  ('ALBORADA', 'EGM959', 'car'),
  ('ALBORADA', 'GIK324', 'car'),
  ('ALBORADA', 'XZN42F', 'car'),
  ('ALBORADA', 'JQT633', 'car'),
  ('ALBORADA', 'AOT26', 'car'),
  ('ALBORADA', 'HGU68H', 'car'),
  ('ALBORADA', 'JLD52F', 'car'),
  ('ALBORADA', 'CPV20', 'car'),
  ('ALBORADA', 'VKP03D', 'car'),
  ('ALBORADA', 'JCW385', 'car'),
  ('ALBORADA', 'MXY983', 'car'),
  ('ALBORADA', 'HFJ09H', 'car'),
  ('ALBORADA', 'NIM39G', 'car'),
  ('ALBORADA', 'RXI74D', 'car'),
  ('BRESCIA', 'FUN200', 'car'),
  ('BRESCIA', 'IAR806', 'car'),
  ('BRESCIA', 'DJP867', 'car'),
  ('BRESCIA', 'ZYA09F', 'car'),
  ('BRESCIA', 'ISG-740', 'car'),
  ('BRESCIA', 'MWP192', 'car'),
  ('BRESCIA', 'GHZ192', 'car'),
  ('BRESCIA', 'ROI56H', 'car'),
  ('BRESCIA', 'DVS91E', 'car'),
  ('PATIO BONITO', 'JBL643', 'car'),
  ('PATIO BONITO', 'HXX239', 'car'),
  ('PATIO BONITO', 'MIW449', 'car'),
  ('PATIO BONITO', 'LFE103', 'car'),
  ('PATIO BONITO', 'PSD764', 'car'),
  ('PATIO BONITO', 'NZH29G', 'car'),
  ('PATIO BONITO', 'CJL86H', 'car'),
  ('PATIO BONITO', 'DSU140', 'car'),
  ('PATIO BONITO', 'RLQ902', 'car'),
  ('PATIO BONITO', 'JOQ194', 'car'),
  ('PATIO BONITO', 'IHS708', 'car'),
  ('PATIO BONITO', 'PMR010', 'car'),
  ('PATIO BONITO', 'MNS475', 'car'),
  ('PATIO BONITO', 'DQM619', 'car'),
  ('PATIO BONITO', 'KPS637', 'car'),
  ('PATIO BONITO', 'MMT846', 'car'),
  ('PATIO BONITO', 'JEW882', 'car'),
  ('PATIO BONITO', 'MHE33G', 'car'),
  ('PATIO BONITO', 'NNM75G', 'car'),
  ('PATIO BONITO', 'EOU983', 'car'),
  ('PATIO BONITO', 'QKP658', 'car'),
  ('PATIO BONITO', 'GFK507', 'car'),
  ('PATIO BONITO', 'EDT83G', 'car'),
  ('SAN SEBASTIAN', 'DFS-472', 'car'),
  ('SAN SEBASTIAN', 'MNR-441', 'car'),
  ('SAN SEBASTIAN', 'LKR-655', 'car'),
  ('SAN SEBASTIAN', 'JIZ-273', 'car'),
  ('SAN SEBASTIAN', 'MIQ048', 'car'),
  ('SAN SEBASTIAN', 'INO413', 'car'),
  ('SAN SEBASTIAN', 'LZX909', 'car'),
  ('SAN SEBASTIAN', 'HRN-28C', 'car'),
  ('SAN SEBASTIAN', 'QLA-50G', 'car'),
  ('SAN SEBASTIAN', 'DIL-152', 'car'),
  ('SAN SEBASTIAN', 'DUM-890', 'car'),
  ('SAN SEBASTIAN', 'GHY-585', 'car'),
  ('SAN SEBASTIAN', 'KUQ-471', 'car'),
  ('SAN SEBASTIAN', 'LEK-369', 'car'),
  ('SAN SEBASTIAN', 'JSS-647', 'car'),
  ('SAN SEBASTIAN', 'EPU-738', 'car'),
  ('SAN SEBASTIAN', 'YQB-82F', 'car'),
  ('SAN SEBASTIAN', 'NGS-870', 'car'),
  ('SAN SEBASTIAN', 'KPU992', 'car'),
  ('SAN SEBASTIAN', 'LGT661', 'car'),
  ('SAN SEBASTIAN', 'JYY-560', 'car'),
  ('SAN SEBASTIAN', 'AIV731', 'car'),
  ('SAN SEBASTIAN', 'NNP-650', 'car'),
  ('TERRABAMBA', 'JOT-146', 'car'),
  ('TERRABAMBA', 'FXD047', 'car'),
  ('TERRABAMBA', 'DEW822', 'car'),
  ('TERRABAMBA', 'LTQ-725', 'car'),
  ('TERRABAMBA', 'BIJ-013', 'car'),
  ('TERRABAMBA', 'JZN283', 'car'),
  ('TERRABAMBA', 'LZV-804', 'car'),
  ('TERRABAMBA', 'JOS-515', 'car'),
  ('TERRABAMBA', 'IAW-488', 'car'),
  ('TERRABAMBA', 'LFO-424', 'car'),
  ('TERRABAMBA', 'DST-572', 'car'),
  ('TERRABAMBA', 'GEY-898', 'car'),
  ('TERRABAMBA', 'IIQ-982', 'car'),
  ('TERRABAMBA', 'MTY623', 'car'),
  ('TERRABAMBA', 'FPR-507', 'car'),
  ('TERRABAMBA', 'GIW-501', 'car'),
  ('TERRABAMBA', 'NVY-183', 'car'),
  ('TERRABAMBA', 'KOM-659', 'car'),
  ('TERRABAMBA', 'KBT-868', 'car'),
  ('TERRABAMBA', 'KPX-703', 'car'),
  ('TERRABAMBA', 'IAX-013', 'car'),
  ('TERRABAMBA', 'JIW-402', 'car'),
  ('TERRABAMBA', 'LZZ-776', 'car'),
  ('TERRABAMBA', 'FCM-505', 'car'),
  ('ALTOS DEL ROSARIO', 'NGT617', 'car'),
  ('ALTOS DEL ROSARIO', 'KPS847', 'car'),
  ('ALTOS DEL ROSARIO', 'LHL925', 'car'),
  ('ALTOS DEL ROSARIO', 'SPS436', 'car'),
  ('ALTOS DEL ROSARIO', 'UEX788', 'car'),
  ('ALTOS DEL ROSARIO', 'LPP156', 'car'),
  ('ALTOS DEL ROSARIO', 'NPN934', 'car'),
  ('ALTOS DEL ROSARIO', 'LKS673', 'car'),
  ('ALTOS DEL ROSARIO', 'NIK638', 'car'),
  ('ALTOS DEL ROSARIO', 'NWL531', 'car'),
  ('ALTOS DEL ROSARIO', 'LCU108', 'car'),
  ('ALTOS DEL ROSARIO', 'NTS417', 'car'),
  ('ALTOS DEL ROSARIO', 'KUQ779', 'car'),
  ('ALTOS DEL ROSARIO', 'HIZ921', 'car'),
  ('ALTOS DEL ROSARIO', 'JSR504', 'car'),
  ('ALTOS DEL ROSARIO', 'FKO199', 'car'),
  ('ALTOS DEL ROSARIO', 'LRX554', 'car'),
  ('ALTOS DEL ROSARIO', 'CWV701', 'car'),
  ('ALTOS DEL ROSARIO', 'KRV019', 'car'),
  ('ALTOS DEL ROSARIO', 'MST123', 'car'),
  ('ALTOS DEL ROSARIO', 'JOR816', 'car'),
  ('ALTOS DEL ROSARIO', 'EBN448', 'car'),
  ('ALTOS DEL ROSARIO', 'FUN577', 'car'),
  ('ALTOS DEL ROSARIO', 'JIY618', 'car'),
  ('ALTOS DEL ROSARIO', 'BXT261', 'car'),
  ('ALTOS DEL ROSARIO', 'GWZ197', 'car'),
  ('ALTOS DEL ROSARIO', 'LCX550', 'car'),
  ('ALTOS DEL ROSARIO', 'PRO758', 'car'),
  ('ALTOS DEL ROSARIO', 'NEW953', 'car'),
  ('ALTOS DEL ROSARIO', 'PMQ552', 'car'),
  ('SENDEROS DE CALASANZ', 'XQS-27H', 'car'),
  ('SENDEROS DE CALASANZ', 'KTN-272', 'car'),
  ('SENDEROS DE CALASANZ', 'NJX-341', 'car'),
  ('SENDEROS DE CALASANZ', 'RZE-588', 'car'),
  ('SENDEROS DE CALASANZ', 'GEW-241', 'car'),
  ('SENDEROS DE CALASANZ', 'NPN-783', 'car'),
  ('SENDEROS DE CALASANZ', 'BBM-11C', 'car'),
  ('SENDEROS DE CALASANZ', 'GEY-890', 'car'),
  ('SENDEROS DE CALASANZ', 'NPL-169', 'car'),
  ('SENDEROS DE CALASANZ', 'MIR-589', 'car'),
  ('SENDEROS DE CALASANZ', 'FER-929', 'car'),
  ('SENDEROS DE CALASANZ', 'IYQ-762', 'car'),
  ('SENDEROS DE CALASANZ', 'KVQ-178', 'car'),
  ('SENDEROS DE CALASANZ', 'PIR-364', 'car'),
  ('SENDEROS DE CALASANZ', 'FWP-402', 'car'),
  ('SENDEROS DE CALASANZ', 'BCB-797', 'car'),
  ('SENDEROS DE CALASANZ', 'ORJ-53D', 'car'),
  ('SENDEROS DE CALASANZ', 'NPQ-039', 'car'),
  ('SENDEROS DE CALASANZ', 'IOS-570', 'car'),
  ('SENDEROS DE CALASANZ', 'KUP-864', 'car'),
  ('SENDEROS DE CALASANZ', 'BWW-807', 'car'),
  ('SENDEROS DE CALASANZ', 'IEW-501', 'car'),
  ('SENDEROS DE CALASANZ', 'LKR-968', 'car'),
  ('SENDEROS DE CALASANZ', 'MSR-617', 'car'),
  ('SENDEROS DE CALASANZ', 'IEL-478', 'car'),
  ('SENDEROS DE CALASANZ', 'VCA-37H', 'car'),
  ('SENDEROS DE CALASANZ', 'LGO-370', 'car'),
  ('SENDEROS DE CALASANZ', 'FHK-102', 'car'),
  ('SENDEROS DE CALASANZ', 'NPP-474', 'car'),
  ('SENDEROS DE CALASANZ', 'WIW-47E', 'car'),
  ('SENDEROS DE CALASANZ', 'KPS-170', 'car'),
  ('SENDEROS DE CALASANZ', 'BAI-740', 'car'),
  ('SENDEROS DE CALASANZ', 'IYP-765', 'car'),
  ('SENDEROS DE CALASANZ', 'JLU-601', 'car'),
  ('SENDEROS DE CALASANZ', 'LXR-191', 'car'),
  ('SENDEROS DE CALASANZ', 'HGY-561', 'car'),
  ('SENDEROS DE CALASANZ', 'PRK-663', 'car'),
  ('SENDEROS DE CALASANZ', 'PRT-856', 'car'),
  ('SENDEROS DE CALASANZ', 'JMO-804', 'car'),
  ('SENDEROS DE CALASANZ', 'DSY-385', 'car'),
  ('SENDEROS DE CALASANZ', 'NVY-58F', 'car'),
  ('SENDEROS DE CALASANZ', 'MSS-837', 'car'),
  ('SENDEROS DE CALASANZ', 'LZZ-051', 'car'),
  ('SENDEROS DE CALASANZ', 'IAQ-13F', 'car'),
  ('SENDEROS DE CALASANZ', 'TPR-18G', 'car'),
  ('SENDEROS DE CALASANZ', 'MGU-94C', 'car'),
  ('SENDEROS DE CALASANZ', 'EGK-992', 'car'),
  ('SENDEROS DE CALASANZ', 'JCQ-204', 'car'),
  ('SENDEROS DE CALASANZ', 'IAQ-127', 'car'),
  ('SENDEROS DE CALASANZ', 'ICP-161', 'car'),
  ('SENDEROS DE CALASANZ', 'LMU-152', 'car'),
  ('SENDEROS DE CALASANZ', 'HYZ-484', 'car'),
  ('SENDEROS DE CALASANZ', 'EIZ-141', 'car'),
  ('SENDEROS DE CALASANZ', 'HZK-436', 'car'),
  ('SENDEROS DE CALASANZ', 'FRQ-060', 'car'),
  ('SENDEROS DE CALASANZ', 'HYR-150', 'car'),
  ('SENDEROS DE CALASANZ', 'GWZ-433', 'car'),
  ('SENDEROS DE CALASANZ', 'GZB-I5D', 'car'),
  ('SENDEROS DE CALASANZ', 'JMU-586', 'car'),
  ('SENDEROS DE CALASANZ', 'IOR-087', 'car'),
  ('SENDEROS DE CALASANZ', 'NPQ-120', 'car'),
  ('SENDEROS DE CALASANZ', 'FBP-297', 'car'),
  ('SENDEROS DE CALASANZ', 'LTS-662', 'car'),
  ('SENDEROS DE CALASANZ', 'JLM-636', 'car'),
  ('DANUBIOS', 'EOQ-17E', 'car'),
  ('DANUBIOS', 'BXS106', 'car'),
  ('DANUBIOS', 'HFL171', 'car'),
  ('DANUBIOS', 'XTG49G', 'car'),
  ('DANUBIOS', 'HEX863', 'car'),
  ('DANUBIOS', 'NDS274', 'car'),
  ('DANUBIOS', 'KBR986', 'car'),
  ('DANUBIOS', 'EGK797', 'car'),
  ('DANUBIOS', 'LUK447', 'car'),
  ('DANUBIOS', 'OHH29G', 'car'),
  ('DANUBIOS', 'SLB49F', 'car'),
  ('DANUBIOS', 'DQT-006', 'car'),
  ('DANUBIOS', 'JOQ457', 'car'),
  ('DANUBIOS', 'JCU104', 'car'),
  ('DANUBIOS', 'BKM255', 'car')
) AS t(site_name, plate, vtype)
JOIN public.sites s ON UPPER(s.name) = UPPER(t.site_name)
  AND s.tenant_id = 'a0000000-0000-0000-0000-000000000001'
ON CONFLICT (tenant_id, site_id, plate) DO NOTHING;
