-- ═══════════════════════════════════════════════════════════
-- AION — Multi-tenant Seed Data
-- Tenant: a0000000-0000-0000-0000-000000000001
-- Auto-generated from 04_seed_vehicles_access.sql
-- ═══════════════════════════════════════════════════════════


-- ── Vehicles Batch 2 (300 plates) ──────────────────
INSERT INTO public.vehicles (tenant_id, site_id, plate, vehicle_type)
SELECT
  'a0000000-0000-0000-0000-000000000001',
  s.id,
  t.plate,
  t.vtype
FROM (VALUES
  ('DANUBIOS', 'IMU-681', 'car'),
  ('DANUBIOS', 'DJK-970', 'car'),
  ('DANUBIOS', 'EOQ17E', 'car'),
  ('DANUBIOS', 'FKE-20', 'car'),
  ('DANUBIOS', 'NES-389', 'car'),
  ('DANUBIOS', 'JHK-11E', 'car'),
  ('DANUBIOS', 'OHH-29G', 'car'),
  ('DANUBIOS', 'JQO-375', 'car'),
  ('DANUBIOS', 'EOM-117', 'car'),
  ('DANUBIOS', 'UEN-264', 'car'),
  ('DANUBIOS', 'JVU-330', 'car'),
  ('DANUBIOS', 'DNS-274', 'car'),
  ('DANUBIOS', 'DGV-386', 'car'),
  ('DANUBIOS', 'PWD-205', 'car'),
  ('ALBORADA', 'GHX-036', 'car'),
  ('ALBORADA', 'HCC-146', 'car'),
  ('ALBORADA', 'DFU-257', 'car'),
  ('ALBORADA', 'MNX-346', 'car'),
  ('ALBORADA', 'DGS-442', 'car'),
  ('ALBORADA', 'MIX-528', 'car'),
  ('ALBORADA', 'KHQ-693', 'car'),
  ('ALBORADA', 'PKB-76E', 'car'),
  ('ALBORADA', 'FBO-85', 'car'),
  ('ALBORADA', 'BXT-972', 'car'),
  ('ALBORADA', 'NPP-050', 'car'),
  ('ALBORADA', 'XYQ-15F', 'car'),
  ('ALBORADA', 'MVS-292', 'car'),
  ('ALBORADA', 'DMK-314', 'car'),
  ('ALBORADA', 'PRO-417', 'car'),
  ('ALBORADA', 'DFT-573', 'car'),
  ('ALBORADA', 'SSJ-60E', 'car'),
  ('ALBORADA', 'NPU-732', 'car'),
  ('ALBORADA', 'TAJ-827', 'car'),
  ('ALBORADA', 'FYZ-902', 'car'),
  ('ALBORADA', 'YPU-05F', 'car'),
  ('ALBORADA', 'LEN-114', 'car'),
  ('ALBORADA', 'INO-276', 'car'),
  ('ALBORADA', 'GIK-324', 'car'),
  ('ALBORADA', 'LAN-432', 'car'),
  ('ALBORADA', 'CFC-54E', 'car'),
  ('ALBORADA', 'GWW-627', 'car'),
  ('ALBORADA', 'JYY-717', 'car'),
  ('ALBORADA', 'JHT-862', 'car'),
  ('ALBORADA', 'DQL-920', 'car'),
  ('ALBORADA', 'PEJ-054', 'car'),
  ('ALBORADA', 'PQL-10H', 'car'),
  ('ALBORADA', 'PMQ-206', 'car'),
  ('ALBORADA', 'NIM-39G', 'car'),
  ('ALBORADA', 'STU-486', 'car'),
  ('ALBORADA', 'KWO-523', 'car'),
  ('ALBORADA', 'MTX-676', 'car'),
  ('ALBORADA', 'SNQ-705', 'car'),
  ('ALBORADA', 'CJY-86H', 'car'),
  ('ALBORADA', 'MXY-983', 'car'),
  ('ALBORADA', 'EIM-085', 'car'),
  ('ALBORADA', 'INF-114', 'car'),
  ('ALBORADA', 'CPV-20', 'car'),
  ('ALBORADA', 'JKR-362', 'car'),
  ('ALBORADA', 'XZN-42F', 'car'),
  ('ALBORADA', 'KRI-579', 'car'),
  ('ALBORADA', 'ZAA-64F', 'car'),
  ('ALBORADA', 'RFT-73G', 'car'),
  ('ALBORADA', 'POV-894', 'car'),
  ('ALBORADA', 'XPF-98H', 'car'),
  ('ALBORADA', 'PBQ-085', 'car'),
  ('ALBORADA', 'HLC-146', 'car'),
  ('ALBORADA', 'JMO-24H', 'car'),
  ('ALBORADA', 'GZN-30F', 'car'),
  ('ALBORADA', 'KWO-526', 'car'),
  ('ALBORADA', 'JOT-633', 'car'),
  ('ALBORADA', 'WWB-71F', 'car'),
  ('ALBORADA', 'BSV-825', 'car'),
  ('ALBORADA', 'DFS-97', 'car'),
  ('ALBORADA', 'KWO-085', 'car'),
  ('ALBORADA', 'PMQ123', 'car'),
  ('ALBORADA', 'AIG-25H', 'car'),
  ('ALBORADA', 'JCW-385', 'car'),
  ('ALBORADA', 'JLD-52F', 'car'),
  ('ALBORADA', 'JIX-691', 'car'),
  ('ALBORADA', 'RXI-74D', 'car'),
  ('ALBORADA', 'RFS-86D', 'car'),
  ('ALBORADA', 'EGM-959', 'car'),
  ('ALBORADA', 'FBQ-088', 'car'),
  ('ALBORADA', 'NNP-118', 'car'),
  ('ALBORADA', 'CUN-229', 'car'),
  ('ALBORADA', 'HNU-358', 'car'),
  ('ALBORADA', 'ITN-50G', 'car'),
  ('ALBORADA', 'KHP-603', 'car'),
  ('ALBORADA', 'UZO-79F', 'car'),
  ('ALBORADA', 'JIY-882', 'car'),
  ('ALBORADA', 'HFK-09H', 'car'),
  ('ALBORADA', 'AOT-26', 'car'),
  ('ALBORADA', 'JLH-36H', 'car'),
  ('ALBORADA', 'KBT-579', 'car'),
  ('ALBORADA', 'GVM-693', 'car'),
  ('ALBORADA', 'ERN-78F', 'car'),
  ('ALBORADA', 'IAY-867', 'car'),
  ('ALBORADA', 'VKP-03D', 'car'),
  ('ALBORADA', 'LPT-238', 'car'),
  ('ALBORADA', 'IOT-338', 'car'),
  ('ALBORADA', 'MIX-523', 'car'),
  ('ALBORADA', 'KHP-683', 'car'),
  ('ALBORADA', 'LXL-762', 'car'),
  ('ALBORADA', 'FBO-085', 'car'),
  ('ALBORADA', 'ZXY-29D', 'car'),
  ('ALBORADA', 'KRW-362', 'car'),
  ('ALBORADA', 'DEU-548', 'car'),
  ('ALBORADA', 'HGU-68H', 'car'),
  ('ALBORADA', 'SNQ-736', 'car'),
  ('ALBORADA', 'KUR-600', 'car'),
  ('ALBORADA', 'DFJ-760', 'car'),
  ('ALBORADA', 'HZN-72H', 'car'),
  ('ALBORADA', 'HUH-32F', 'car'),
  ('ALBORADA', 'EPU-76E', 'car'),
  ('ALBORADA', 'TRY-37G', 'car'),
  ('ALBORADA', 'LLW-724', 'car'),
  ('ALBORADA', 'LQJ-34G', 'car'),
  ('ALBORADA', 'QKQ-345', 'car'),
  ('ALBORADA', 'FPU-33H', 'car'),
  ('PORTAL PLAZA', 'KCC-02B', 'car'),
  ('PORTAL PLAZA', 'LUE-12H', 'car'),
  ('PORTAL PLAZA', 'DFN-28G', 'car'),
  ('PORTAL PLAZA', 'WWT-39F', 'car'),
  ('PORTAL PLAZA', 'UHK-40C', 'car'),
  ('PORTAL PLAZA', 'LRV-596', 'car'),
  ('PORTAL PLAZA', 'ERX67F', 'car'),
  ('PORTAL PLAZA', 'LUB-76F', 'car'),
  ('PORTAL PLAZA', 'RBG-80F', 'car'),
  ('PORTAL PLAZA', 'RIE-98G', 'car'),
  ('PORTAL PLAZA', 'PIR-158', 'car'),
  ('PORTAL PLAZA', 'PIR-208', 'car'),
  ('PORTAL PLAZA', 'AHJ-35H', 'car'),
  ('PORTAL PLAZA', 'AHW-47H', 'car'),
  ('PORTAL PLAZA', 'PMM-536', 'car'),
  ('PORTAL PLAZA', 'VTI-66D', 'car'),
  ('PORTAL PLAZA', 'KQQ-705', 'car'),
  ('PORTAL PLAZA', 'LLT-80G', 'car'),
  ('PORTAL PLAZA', 'FWE-97G', 'car'),
  ('PORTAL PLAZA', 'NMW-17G', 'car'),
  ('PORTAL PLAZA', 'REH-44D', 'car'),
  ('PORTAL PLAZA', 'EVT-516', 'car'),
  ('PORTAL PLAZA', 'DFI-66G', 'car'),
  ('PORTAL PLAZA', 'XJT-726', 'car'),
  ('PORTAL PLAZA', 'OWS-87F', 'car'),
  ('PORTAL PLAZA', 'VBY-90H', 'car'),
  ('PORTAL PLAZA', 'EMN-62H', 'car'),
  ('PORTAL PLAZA', 'GEP-866', 'car'),
  ('PORTAL PLAZA', 'CDB-95I', 'car'),
  ('PORTAL PLAZA', 'AGT-60H', 'car'),
  ('TERRAZZINO', 'CGU-04E', 'car'),
  ('TERRAZZINO', 'LKR-185', 'car'),
  ('TERRAZZINO', 'KOP-209', 'car'),
  ('TERRAZZINO', 'MUL-309', 'car'),
  ('TERRAZZINO', 'ZYT-472', 'car'),
  ('TERRAZZINO', 'KZR-535', 'car'),
  ('TERRAZZINO', 'GDX-687', 'car'),
  ('TERRAZZINO', 'LCY-725', 'car'),
  ('TERRAZZINO', 'JCS-830', 'car'),
  ('TERRAZZINO', 'ISU-922', 'car'),
  ('TERRAZZINO', 'XLX-19E', 'car'),
  ('TERRAZZINO', 'FQB-217', 'car'),
  ('TERRAZZINO', 'MVU-399', 'car'),
  ('TERRAZZINO', 'GSR-492', 'car'),
  ('TERRAZZINO', 'HZO-531', 'car'),
  ('TERRAZZINO', 'EKX-627', 'car'),
  ('TERRAZZINO', 'HZN-798', 'car'),
  ('TERRAZZINO', 'EIK-821', 'car'),
  ('TERRAZZINO', 'EPT-916', 'car'),
  ('TERRAZZINO', 'KHK-130', 'car'),
  ('TERRAZZINO', 'HNV-257', 'car'),
  ('TERRAZZINO', 'QIY-386', 'car'),
  ('TERRAZZINO', 'PMO-434', 'car'),
  ('TERRAZZINO', 'JEX-529', 'car'),
  ('TERRAZZINO', 'UST-651', 'car'),
  ('TERRAZZINO', 'LKR-749', 'car'),
  ('TERRAZZINO', 'LGQ-882', 'car'),
  ('TERRAZZINO', 'PRX-915', 'car'),
  ('TERRAZZINO', 'EKQ-198', 'car'),
  ('TERRAZZINO', 'USW-256', 'car'),
  ('TERRAZZINO', 'BWG-324', 'car'),
  ('TERRAZZINO', 'PRQ-403', 'car'),
  ('TERRAZZINO', 'NXB-54H', 'car'),
  ('TERRAZZINO', 'IOJ-60E', 'car'),
  ('TERRAZZINO', 'LMZ-828', 'car'),
  ('TERRAZZINO', 'KTX-913', 'car'),
  ('TERRAZZINO', 'KRW-176', 'car'),
  ('TERRAZZINO', 'TZN-252', 'car'),
  ('TERRAZZINO', 'UBL-652', 'car'),
  ('TERRAZZINO', 'SIF-19C', 'car'),
  ('APARTACASAS', 'EOM-091', 'car'),
  ('APARTACASAS', 'IHT-102', 'car'),
  ('APARTACASAS', 'MJM-271', 'car'),
  ('APARTACASAS', 'WTB-32D', 'car'),
  ('APARTACASAS', 'ZON-42C', 'car'),
  ('APARTACASAS', 'IUG-52B', 'car'),
  ('APARTACASAS', 'LGR-659', 'car'),
  ('APARTACASAS', 'USR-79D', 'car'),
  ('APARTACASAS', 'NOH-85G', 'car'),
  ('APARTACASAS', 'ESP-943', 'car'),
  ('APARTACASAS', 'RGO-10G', 'car'),
  ('APARTACASAS', 'GEM-290', 'car'),
  ('APARTACASAS', 'ANQ-39H', 'car'),
  ('APARTACASAS', 'IMN-411', 'car'),
  ('APARTACASAS', 'HXY-512', 'car'),
  ('APARTACASAS', 'XRT-66E', 'car'),
  ('APARTACASAS', 'IHX-74F', 'car'),
  ('APARTACASAS', 'JQQ-868', 'car'),
  ('APARTACASAS', 'DEQ-923', 'car'),
  ('APARTACASAS', 'GIK-255', 'car'),
  ('APARTACASAS', 'JIZ-384', 'car'),
  ('APARTACASAS', 'DIL-477', 'car'),
  ('APARTACASAS', 'FGP-554', 'car'),
  ('APARTACASAS', 'TMU-668', 'car'),
  ('APARTACASAS', 'ELK-765', 'car'),
  ('APARTACASAS', 'JKL-873', 'car'),
  ('APARTACASAS', 'XEH-94D', 'car'),
  ('APARTACASAS', 'ITZ-219', 'car'),
  ('APARTACASAS', 'OJQ-438', 'car'),
  ('APARTACASAS', 'HNW-684', 'car'),
  ('APARTACASAS', 'EWO-743', 'car'),
  ('APARTACASAS', 'QAJ-656', 'car'),
  ('APARTACASAS', 'LQL-777', 'car'),
  ('APARTACASAS', 'LZW-766', 'car'),
  ('APARTACASAS', 'TLY-76C', 'car'),
  ('PATIO BONITO', 'NGT-060', 'car'),
  ('PATIO BONITO', 'JPU-174', 'car'),
  ('PATIO BONITO', 'NZH-29G', 'car'),
  ('PATIO BONITO', 'EFV-362', 'car'),
  ('PATIO BONITO', 'NPL-475', 'car'),
  ('PATIO BONITO', 'GFK-507', 'car'),
  ('PATIO BONITO', 'MIK-649', 'car'),
  ('PATIO BONITO', 'IHS-708', 'car'),
  ('PATIO BONITO', 'EDT-83G', 'car'),
  ('PATIO BONITO', 'RLQ-902', 'car'),
  ('PATIO BONITO', 'GRM-016', 'car'),
  ('PATIO BONITO', 'DSU-140', 'car'),
  ('PATIO BONITO', 'CEO-26B', 'car'),
  ('PATIO BONITO', 'MHE-33G', 'car'),
  ('PATIO BONITO', 'LRS-408', 'car'),
  ('PATIO BONITO', 'FOK-545', 'car'),
  ('PATIO BONITO', 'DQM-619', 'car'),
  ('PATIO BONITO', 'PSD-764', 'car'),
  ('PATIO BONITO', 'HFL-850', 'car'),
  ('PATIO BONITO', 'VES-90F', 'car'),
  ('PATIO BONITO', 'JOQ-194', 'car'),
  ('PATIO BONITO', 'HXX-239', 'car'),
  ('PATIO BONITO', 'LKO-354', 'car'),
  ('PATIO BONITO', 'PQU-476', 'car'),
  ('PATIO BONITO', 'NFJ-654', 'car'),
  ('PATIO BONITO', 'NNM-75G', 'car'),
  ('PATIO BONITO', 'CJL-86H', 'car'),
  ('PATIO BONITO', 'EOU-983', 'car'),
  ('PATIO BONITO', 'LFE-103', 'car'),
  ('PATIO BONITO', 'DRL-219', 'car'),
  ('PATIO BONITO', 'LXQ-398', 'car'),
  ('PATIO BONITO', 'MNS-475', 'car'),
  ('PATIO BONITO', 'JBL-643', 'car'),
  ('PATIO BONITO', 'MMT-846', 'car'),
  ('PATIO BONITO', 'TML-94F', 'car'),
  ('PATIO BONITO', 'JPU-179', 'car'),
  ('PATIO BONITO', 'EVO-376', 'car'),
  ('PATIO BONITO', 'MNK-421', 'car'),
  ('PATIO BONITO', 'NPR-671', 'car'),
  ('PATIO BONITO', 'JEW-882', 'car'),
  ('PATIO BONITO', 'NJR-166', 'car'),
  ('PATIO BONITO', 'MIW-449', 'car'),
  ('PATIO BONITO', 'PMR-110', 'car'),
  ('TORRE LUCIA', 'MZL43F', 'car'),
  ('TORRE LUCIA', 'PIS-110', 'car'),
  ('TORRE LUCIA', 'EKS-217', 'car'),
  ('TORRE LUCIA', 'ITY612', 'car'),
  ('TORRE LUCIA', 'DBM-162', 'car'),
  ('TORRE LUCIA', 'FIS-859', 'car'),
  ('TORRE LUCIA', 'KON-473', 'car'),
  ('TORRE LUCIA', 'LRO-186', 'car'),
  ('TORRE LUCIA', 'GEL-848', 'car'),
  ('TORRE LUCIA', 'SNY-471', 'car'),
  ('TORRE LUCIA', 'HCH-83D', 'car'),
  ('TORRE LUCIA', 'NUU671', 'car'),
  ('TORRE LUCIA', 'DTZ-398', 'car'),
  ('TORRE LUCIA', 'EIA-33E', 'car'),
  ('TORRE LUCIA', 'DHW-968', 'car'),
  ('TORRE LUCIA', 'HOP-36G', 'car'),
  ('TORRE LUCIA', 'FGU-947', 'car'),
  ('TORRE LUCIA', 'YDL59E', 'car'),
  ('TORRE LUCIA', 'EIP12E', 'car'),
  ('TORRE LUCIA', 'JQS586', 'car'),
  ('TORRE LUCIA', 'PMQ-452', 'car'),
  ('TORRE LUCIA', 'JCZ-527', 'car'),
  ('TORRE LUCIA', 'LUO-04D', 'car'),
  ('TORRE LUCIA', 'NPN-697', 'car'),
  ('TORRE LUCIA', 'EIM-324', 'car'),
  ('TORRE LUCIA', 'EPU-357', 'car'),
  ('TORRE LUCIA', 'MTX-160', 'car'),
  ('TORRE LUCIA', 'CXZ-330', 'car'),
  ('TORRE LUCIA', 'JCS-856', 'car'),
  ('TORRE LUCIA', 'BXW-254', 'car'),
  ('TORRE LUCIA', 'LUV36H', 'car'),
  ('TORRE LUCIA', 'KLZ800', 'car'),
  ('TORRE LUCIA', 'FJR972', 'car')
) AS t(site_name, plate, vtype)
JOIN public.sites s ON UPPER(s.name) = UPPER(t.site_name)
  AND s.tenant_id = 'a0000000-0000-0000-0000-000000000001'
ON CONFLICT (tenant_id, site_id, plate) DO NOTHING;
