-- ═══════════════════════════════════════════════════════════
-- AION — Multi-tenant Seed Data
-- Tenant: a0000000-0000-0000-0000-000000000001
-- Auto-generated from 04_seed_vehicles_access.sql
-- ═══════════════════════════════════════════════════════════


-- ── Vehicles Batch 4 (106 plates) ──────────────────
INSERT INTO public.vehicles (tenant_id, site_id, plate, vehicle_type)
SELECT
  'a0000000-0000-0000-0000-000000000001',
  s.id,
  t.plate,
  t.vtype
FROM (VALUES
  ('DANUBIOS', 'DEU348', 'car'),
  ('DANUBIOS', 'WMQ251', 'car'),
  ('DANUBIOS', 'LZW199', 'car'),
  ('DANUBIOS', 'NNR912', 'car'),
  ('DANUBIOS', 'LKR632', 'car'),
  ('DANUBIOS', 'HYR516', 'car'),
  ('DANUBIOS', 'UZK51A', 'car'),
  ('DANUBIOS', 'FKE20', 'car'),
  ('DANUBIOS', 'DEQ959', 'car'),
  ('DANUBIOS', 'RZI529', 'car'),
  ('DANUBIOS', 'BZJ308', 'car'),
  ('DANUBIOS', 'DJK970', 'car'),
  ('DANUBIOS', 'DGY351', 'car'),
  ('DANUBIOS', 'LGN553', 'car'),
  ('DANUBIOS', 'EHK300', 'car'),
  ('DANUBIOS', 'GCR816', 'car'),
  ('DANUBIOS', 'JSU838', 'car'),
  ('DANUBIOS', 'FYW738', 'car'),
  ('DANUBIOS', 'LEQ-334', 'car'),
  ('DANUBIOS', 'NGS-389', 'car'),
  ('DANUBIOS', 'INQ270', 'car'),
  ('DANUBIOS', 'EGK374', 'car'),
  ('DANUBIOS', 'JIV767', 'car'),
  ('DANUBIOS', 'LSN-056', 'car'),
  ('DANUBIOS', 'IYQ982', 'car'),
  ('DANUBIOS', 'ISD13B', 'car'),
  ('DANUBIOS', 'NWL439', 'car'),
  ('DANUBIOS', 'BXB255', 'car'),
  ('DANUBIOS', 'ZID206', 'car'),
  ('DANUBIOS', 'JKO375', 'car'),
  ('DANUBIOS', 'ISV037', 'car'),
  ('TERRAZZINO', 'GDZ687', 'car'),
  ('TERRAZZINO', 'ISU922', 'car'),
  ('TERRAZZINO', 'LKR185', 'car'),
  ('TERRAZZINO', 'YAB57F', 'car'),
  ('TERRAZZINO', 'EPT916', 'car'),
  ('TERRAZZINO', 'CGU04E', 'car'),
  ('TERRAZZINO', 'MUL309', 'car'),
  ('TERRAZZINO', 'JCS830', 'car'),
  ('TERRAZZINO', 'UST651', 'car'),
  ('TERRAZZINO', 'KOP209', 'car'),
  ('TERRAZZINO', 'HZN798', 'car'),
  ('TERRAZZINO', 'KTX913', 'car'),
  ('TERRAZZINO', 'BWG324', 'car'),
  ('TERRAZZINO', 'GSR492', 'car'),
  ('TERRAZZINO', 'FQB217', 'car'),
  ('TERRAZZINO', 'HNV257', 'car'),
  ('TERRAZZINO', 'EIK821', 'car'),
  ('TERRAZZINO', 'MVU399', 'car'),
  ('TERRAZZINO', 'KHK130', 'car'),
  ('TERRAZZINO', 'KZR535', 'car'),
  ('TERRAZZINO', 'LKR749', 'car'),
  ('TERRAZZINO', 'HZO531', 'car'),
  ('TERRAZZINO', 'IOJ60E', 'car'),
  ('PORTAL PLAZA', 'GLA-60F', 'car'),
  ('PORTAL PLAZA', 'RHX-71F', 'car'),
  ('PORTAL PLAZA', 'ERX-67F', 'car'),
  ('PORTAL PLAZA', 'UHK40C', 'car'),
  ('PORTAL PLAZA', 'DFD-86A', 'car'),
  ('PORTAL PLAZA', 'LLT-8OG', 'car'),
  ('PORTAL PLAZA', 'OKO-57G', 'car'),
  ('PORTAL PLAZA', 'LRB-596', 'car'),
  ('PORTAL PLAZA', 'LUE12H', 'car'),
  ('PORTAL PLAZA', 'PMM536', 'car'),
  ('PORTAL PLAZA', 'AHJ35H', 'car'),
  ('PORTAL PLAZA', 'RIE98G', 'car'),
  ('PORTAL PLAZA', 'EMN-62', 'car'),
  ('PORTAL PLAZA', 'REH44D', 'car'),
  ('PORTALEGRE', 'IXJ-196', 'car'),
  ('PORTALEGRE', 'DFU-565', 'car'),
  ('PORTALEGRE', 'FAN-938', 'car'),
  ('PORTALEGRE', 'HQO-854', 'car'),
  ('PORTALEGRE', 'BRL-875', 'car'),
  ('PORTALEGRE', 'LKQ357', 'car'),
  ('PORTALEGRE', 'MYZ-71F', 'car'),
  ('PORTALEGRE', 'KTY-953', 'car'),
  ('PORTALEGRE', 'FXO-122', 'car'),
  ('PORTALEGRE', 'DTH-856', 'car'),
  ('PORTALEGRE', 'EGZ-317', 'car'),
  ('PORTALEGRE', 'FXQ-031', 'car'),
  ('PORTALEGRE', 'DJN-704', 'car'),
  ('PORTALEGRE', 'LGQ-575', 'car'),
  ('PORTALEGRE', 'NNQ-161', 'car'),
  ('PORTALEGRE', 'JOR-677', 'car'),
  ('PORTALEGRE', 'DSX-007', 'car'),
  ('PORTALEGRE', 'HNZ-806', 'car'),
  ('PORTALEGRE', 'EGO-048', 'car'),
  ('PORTALEGRE', 'EOV-687', 'car'),
  ('PORTALEGRE', 'IGU496', 'car'),
  ('PORTALEGRE', 'BCU352', 'car'),
  ('PORTALEGRE', 'NPR-787', 'car'),
  ('PORTALEGRE', 'KYW-77E', 'car'),
  ('PORTALEGRE', 'LKT-799', 'car'),
  ('PORTALEGRE', 'BBU-659', 'car'),
  ('LUBECK', 'LEL-955', 'car'),
  ('LUBECK', 'LMP-167', 'car'),
  ('LUBECK', 'DIU-770', 'car'),
  ('LUBECK', 'JVY129', 'car'),
  ('LUBECK', 'JKM-259', 'car'),
  ('LUBECK', 'NHX777', 'car'),
  ('QUINTAS SANTA MARIA', 'SAF-31E', 'car'),
  ('QUINTAS SANTA MARIA', 'GHZ820', 'car'),
  ('QUINTAS SANTA MARIA', 'GDX592', 'car'),
  ('QUINTAS SANTA MARIA', 'MNJ953', 'car'),
  ('QUINTAS SANTA MARIA', 'NUZ253', 'car'),
  ('QUINTAS SANTA MARIA', 'UEN-962', 'car')
) AS t(site_name, plate, vtype)
JOIN public.sites s ON UPPER(s.name) = UPPER(t.site_name)
  AND s.tenant_id = 'a0000000-0000-0000-0000-000000000001'
ON CONFLICT (tenant_id, site_id, plate) DO NOTHING;
