import { pgTable, uuid, text, integer, boolean, timestamp, jsonb } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { tenants } from './tenants.js';

export const sites = pgTable('sites', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  slug: text('slug'),
  siteSheet: text('site_sheet'),
  address: text('address'),
  latitude: text('latitude'),
  longitude: text('longitude'),
  timezone: text('timezone').notNull().default('UTC'),
  wanIp: text('wan_ip'),
  status: text('status').notNull().default('unknown'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const deviceGroups = pgTable('device_groups', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  siteId: uuid('site_id').notNull().references(() => sites.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  description: text('description'),
});

export const devices = pgTable('devices', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  siteId: uuid('site_id').notNull().references(() => sites.id, { onDelete: 'cascade' }),
  groupId: uuid('group_id').references(() => deviceGroups.id, { onDelete: 'set null' }),
  name: text('name').notNull(),
  deviceSlug: text('device_slug'),
  type: text('type').notNull().default('camera'),
  brand: text('brand').default('generic_onvif'),
  model: text('model').default(''),
  ipAddress: text('ip_address'),
  port: integer('port'),
  httpPort: integer('http_port'),
  rtspPort: integer('rtsp_port').default(554),
  onvifPort: integer('onvif_port').default(80),
  username: text('username'),
  password: text('password'),
  subnetMask: text('subnet_mask'),
  gateway: text('gateway'),
  operator: text('operator'),
  serialNumber: text('serial_number'),
  firmwareVersion: text('firmware_version'),
  macAddress: text('mac_address'),
  status: text('status').notNull().default('unknown'),
  channels: integer('channels').notNull().default(1),
  capabilities: jsonb('capabilities').notNull().default({}),
  tags: text('tags').array().default(sql`'{}'::text[]`),
  notes: text('notes'),
  appName: text('app_name'),
  appId: text('app_id'),
  extension: text('extension'),
  outboundCall: text('outbound_call'),
  connectionType: text('connection_type'),
  apsCount: integer('aps_count'),
  antennasCount: integer('antennas_count'),
  camerasCount: integer('cameras_count'),
  analogCamerasCount: integer('analog_cameras_count'),
  missingFields: text('missing_fields'),
  credentialsEncrypted: boolean('credentials_encrypted').notNull().default(false),
  sourceSheet: text('source_sheet'),
  lastSeen: timestamp('last_seen', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
